<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ksehgal" name="Default test" tests="5" failures="0" timestamp="15 Sep 2014 06:24:29 GMT" time="0.207" errors="0">
  <testcase name="@BeforeClass refreshPageAndVerifyLoad" time="0.0" classname="alerts.AlertsExerciseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at alerts.AlertsExerciseTest.refreshPageAndVerifyLoad(AlertsExerciseTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- @BeforeClass refreshPageAndVerifyLoad -->
  <testcase name="@BeforeClass startFF" time="0.0" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- @BeforeClass startFF -->
  <testcase name="@AfterClass stopFF" time="0.0" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- @AfterClass stopFF -->
  <testcase name="confirmAlertTestCancel" time="0.002" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- confirmAlertTestCancel -->
  <testcase name="confirmAlertTestOK" time="0.004" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- confirmAlertTestOK -->
  <testcase name="plainAlertTest" time="0.002" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- plainAlertTest -->
  <testcase name="promptAlertTestCancel" time="0.002" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- promptAlertTestCancel -->
  <testcase name="promptAlertTestOK" time="0.002" classname="alerts.AlertsExerciseTest">
    <skipped/>
  </testcase> <!-- promptAlertTestOK -->
</testsuite> <!-- Default test -->
